version: "2"

run:
  timeout: 5m
  go: "1.25"

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: github.com/austinwofford/account-management

linters:
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    presets:
      - std-error-handling