version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
  exclusions:
    presets:
      - std-error-handling
      - comments
      - common-false-positives

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: github.com/austinwofford/account-management
