services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: account_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  account-management:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./web:/srv/web
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - account-management
    networks:
      - app-network

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9999:8080"
    networks:
      - app-network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  app-network:
    driver: bridge